[2022-12-18T10:18:39.014+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Can_I_change_name_to_this.load_counter_to_pg manual__2022-12-18T10:17:01.135256+00:00 [queued]>
[2022-12-18T10:18:39.039+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Can_I_change_name_to_this.load_counter_to_pg manual__2022-12-18T10:17:01.135256+00:00 [queued]>
[2022-12-18T10:18:39.041+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-18T10:18:39.043+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-18T10:18:39.060+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-18T10:18:39.115+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): load_counter_to_pg> on 2022-12-18 10:17:01.135256+00:00
[2022-12-18T10:18:39.136+0000] {standard_task_runner.py:55} INFO - Started process 282 to run task
[2022-12-18T10:18:39.146+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Can_I_change_name_to_this', 'load_counter_to_pg', 'manual__2022-12-18T10:17:01.135256+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmp89cgcjnn']
[2022-12-18T10:18:39.149+0000] {standard_task_runner.py:83} INFO - Job 145: Subtask load_counter_to_pg
[2022-12-18T10:18:39.286+0000] {task_command.py:389} INFO - Running <TaskInstance: Can_I_change_name_to_this.load_counter_to_pg manual__2022-12-18T10:17:01.135256+00:00 [running]> on host 502390ac5559
[2022-12-18T10:18:39.385+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Can_I_change_name_to_this
AIRFLOW_CTX_TASK_ID=load_counter_to_pg
AIRFLOW_CTX_EXECUTION_DATE=2022-12-18T10:17:01.135256+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-18T10:17:01.135256+00:00
[2022-12-18T10:18:39.391+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-18T10:18:39.395+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/tasks/redshift/counter_load_to_redshift.py']
[2022-12-18T10:18:39.417+0000] {subprocess.py:86} INFO - Output:
[2022-12-18T10:18:39.813+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-18T10:18:39.816+0000] {subprocess.py:93} INFO -   File "/opt/***/tasks/redshift/counter_load_to_redshift.py", line 8, in <module>
[2022-12-18T10:18:39.819+0000] {subprocess.py:93} INFO -     from logger.Logger import Log
[2022-12-18T10:18:39.821+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'logger'
[2022-12-18T10:18:39.837+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2022-12-18T10:18:39.883+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-12-18T10:18:39.901+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=Can_I_change_name_to_this, task_id=load_counter_to_pg, execution_date=20221218T101701, start_date=20221218T101839, end_date=20221218T101839
[2022-12-18T10:18:39.930+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 145 for task load_counter_to_pg (Bash command failed. The command returned a non-zero exit code 1.; 282)
[2022-12-18T10:18:39.970+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-18T10:18:40.026+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
