[2022-11-28T02:32:20.869+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Can_I_change_name_to_this.task_1 manual__2022-11-28T02:31:38.017099+00:00 [queued]>
[2022-11-28T02:32:20.897+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Can_I_change_name_to_this.task_1 manual__2022-11-28T02:31:38.017099+00:00 [queued]>
[2022-11-28T02:32:20.899+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-28T02:32:20.905+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-28T02:32:20.907+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-28T02:32:20.931+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): task_1> on 2022-11-28 02:31:38.017099+00:00
[2022-11-28T02:32:20.944+0000] {standard_task_runner.py:55} INFO - Started process 198 to run task
[2022-11-28T02:32:20.947+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Can_I_change_name_to_this', 'task_1', 'manual__2022-11-28T02:31:38.017099+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmp7dbgphbu']
[2022-11-28T02:32:20.950+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask task_1
[2022-11-28T02:32:21.058+0000] {task_command.py:376} INFO - Running <TaskInstance: Can_I_change_name_to_this.task_1 manual__2022-11-28T02:31:38.017099+00:00 [running]> on host 7667c9be398a
[2022-11-28T02:32:21.144+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Can_I_change_name_to_this
AIRFLOW_CTX_TASK_ID=task_1
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T02:31:38.017099+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-28T02:31:38.017099+00:00
[2022-11-28T02:32:21.153+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-28T02:32:21.156+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***s/tasks/lol_champ_basic_stat.py ']
[2022-11-28T02:32:21.168+0000] {subprocess.py:86} INFO - Output:
[2022-11-28T02:32:21.298+0000] {subprocess.py:93} INFO - python: can't open file '/opt/***s/tasks/lol_champ_basic_stat.py': [Errno 2] No such file or directory
[2022-11-28T02:32:21.308+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2022-11-28T02:32:21.340+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-11-28T02:32:21.347+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=Can_I_change_name_to_this, task_id=task_1, execution_date=20221128T023138, start_date=20221128T023220, end_date=20221128T023221
[2022-11-28T02:32:21.371+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task task_1 (Bash command failed. The command returned a non-zero exit code 2.; 198)
[2022-11-28T02:32:21.415+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-28T02:32:21.530+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
