[2022-12-26T10:02:17.884+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Can_I_change_name_to_this.basic_data_cleansing scheduled__2022-12-25T10:00:00+00:00 [queued]>
[2022-12-26T10:02:17.956+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Can_I_change_name_to_this.basic_data_cleansing scheduled__2022-12-25T10:00:00+00:00 [queued]>
[2022-12-26T10:02:17.968+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-26T10:02:17.973+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-26T10:02:17.975+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-26T10:02:18.037+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): basic_data_cleansing> on 2022-12-25 10:00:00+00:00
[2022-12-26T10:02:18.068+0000] {standard_task_runner.py:55} INFO - Started process 164 to run task
[2022-12-26T10:02:18.125+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Can_I_change_name_to_this', 'basic_data_cleansing', 'scheduled__2022-12-25T10:00:00+00:00', '--job-id', '268', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpcvbeic3_']
[2022-12-26T10:02:18.132+0000] {standard_task_runner.py:83} INFO - Job 268: Subtask basic_data_cleansing
[2022-12-26T10:02:18.512+0000] {task_command.py:389} INFO - Running <TaskInstance: Can_I_change_name_to_this.basic_data_cleansing scheduled__2022-12-25T10:00:00+00:00 [running]> on host 502390ac5559
[2022-12-26T10:02:18.982+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Can_I_change_name_to_this
AIRFLOW_CTX_TASK_ID=basic_data_cleansing
AIRFLOW_CTX_EXECUTION_DATE=2022-12-25T10:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-25T10:00:00+00:00
[2022-12-26T10:02:18.988+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-26T10:02:19.008+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/tasks/data_cleansing_basic_stat.py']
[2022-12-26T10:02:19.096+0000] {subprocess.py:86} INFO - Output:
[2022-12-26T10:02:25.058+0000] {subprocess.py:93} INFO - 2022-12-26 10:02:25 +0000 - dagster - DEBUG - data_cleansing_whole_job - 395075b2-1f79-4a50-be1a-e667df529b13 - 167 - RUN_START - Started execution of run for "data_cleansing_whole_job".
[2022-12-26T10:02:25.088+0000] {subprocess.py:93} INFO - 2022-12-26 10:02:25 +0000 - dagster - DEBUG - data_cleansing_whole_job - 395075b2-1f79-4a50-be1a-e667df529b13 - 167 - ENGINE_EVENT - Executing steps in process (pid: 167)
[2022-12-26T10:02:25.094+0000] {subprocess.py:93} INFO - 2022-12-26 10:02:25 +0000 - dagster - DEBUG - data_cleansing_whole_job - 395075b2-1f79-4a50-be1a-e667df529b13 - 167 - RESOURCE_INIT_STARTED - Starting initialization of resources [io_manager].
[2022-12-26T10:02:25.099+0000] {subprocess.py:93} INFO - 2022-12-26 10:02:25 +0000 - dagster - DEBUG - data_cleansing_whole_job - 395075b2-1f79-4a50-be1a-e667df529b13 - 167 - RESOURCE_INIT_SUCCESS - Finished initialization of resources [io_manager].
[2022-12-26T10:02:25.104+0000] {subprocess.py:93} INFO - 2022-12-26 10:02:25 +0000 - dagster - DEBUG - data_cleansing_whole_job - 395075b2-1f79-4a50-be1a-e667df529b13 - 167 - LOGS_CAPTURED - Started capturing logs in process (pid: 167).
[2022-12-26T10:02:25.108+0000] {subprocess.py:93} INFO - 2022-12-26 10:02:25 +0000 - dagster - DEBUG - data_cleansing_whole_job - 395075b2-1f79-4a50-be1a-e667df529b13 - 167 - reading_json - STEP_START - Started execution of step "reading_json".
[2022-12-26T10:02:25.109+0000] {subprocess.py:93} INFO - 2022-12-26 10:02:25 +0000 - dagster - ERROR - data_cleansing_whole_job - 395075b2-1f79-4a50-be1a-e667df529b13 - 167 - reading_json - STEP_FAILURE - Execution of step "reading_json" failed.
[2022-12-26T10:02:25.110+0000] {subprocess.py:93} INFO - 
[2022-12-26T10:02:25.114+0000] {subprocess.py:93} INFO - dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "reading_json"::
[2022-12-26T10:02:25.118+0000] {subprocess.py:93} INFO - 
[2022-12-26T10:02:25.120+0000] {subprocess.py:93} INFO - ValueError: Expected object or value
[2022-12-26T10:02:25.124+0000] {subprocess.py:93} INFO - 
[2022-12-26T10:02:25.125+0000] {subprocess.py:93} INFO - Stack Trace:
[2022-12-26T10:02:25.127+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_core/execution/plan/utils.py", line 56, in op_execution_error_boundary
[2022-12-26T10:02:25.128+0000] {subprocess.py:93} INFO -     yield
[2022-12-26T10:02:25.129+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_utils/__init__.py", line 458, in iterate_with_context
[2022-12-26T10:02:25.134+0000] {subprocess.py:93} INFO -     next_output = next(iterator)
[2022-12-26T10:02:25.137+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_core/execution/plan/compute_generator.py", line 75, in _coerce_solid_compute_fn_to_iterator
[2022-12-26T10:02:25.139+0000] {subprocess.py:93} INFO -     result = fn(context, **kwargs) if context_arg_provided else fn(**kwargs)
[2022-12-26T10:02:25.140+0000] {subprocess.py:93} INFO -   File "/opt/***/tasks/data_cleansing_basic_stat.py", line 22, in reading_json
[2022-12-26T10:02:25.142+0000] {subprocess.py:93} INFO -     df = pd.read_json("/opt/***/zone1/lol_basic_stat.json",lines=True)
[2022-12-26T10:02:25.143+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
[2022-12-26T10:02:25.144+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2022-12-26T10:02:25.146+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
[2022-12-26T10:02:25.147+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2022-12-26T10:02:25.149+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
[2022-12-26T10:02:25.151+0000] {subprocess.py:93} INFO -     return json_reader.read()
[2022-12-26T10:02:25.153+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 746, in read
[2022-12-26T10:02:25.155+0000] {subprocess.py:93} INFO -     obj = self._get_object_parser(self._combine_lines(data_lines))
[2022-12-26T10:02:25.156+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
[2022-12-26T10:02:25.158+0000] {subprocess.py:93} INFO -     obj = FrameParser(json, **kwargs).parse()
[2022-12-26T10:02:25.161+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
[2022-12-26T10:02:25.163+0000] {subprocess.py:93} INFO -     self._parse_no_numpy()
[2022-12-26T10:02:25.165+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
[2022-12-26T10:02:25.167+0000] {subprocess.py:93} INFO -     loads(json, precise_float=self.precise_float), dtype=None
[2022-12-26T10:02:25.183+0000] {subprocess.py:93} INFO - 
[2022-12-26T10:02:25.186+0000] {subprocess.py:93} INFO - 2022-12-26 10:02:25 +0000 - dagster - ERROR - data_cleansing_whole_job - 395075b2-1f79-4a50-be1a-e667df529b13 - 167 - RUN_FAILURE - Execution of run for "data_cleansing_whole_job" failed. An exception was thrown during execution.
[2022-12-26T10:02:25.188+0000] {subprocess.py:93} INFO - 
[2022-12-26T10:02:25.189+0000] {subprocess.py:93} INFO - ValueError: Expected object or value
[2022-12-26T10:02:25.191+0000] {subprocess.py:93} INFO - 
[2022-12-26T10:02:25.193+0000] {subprocess.py:93} INFO - Stack Trace:
[2022-12-26T10:02:25.194+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_core/execution/api.py", line 1089, in pipeline_execution_iterator
[2022-12-26T10:02:25.196+0000] {subprocess.py:93} INFO -     for event in pipeline_context.executor.execute(pipeline_context, execution_plan):
[2022-12-26T10:02:25.197+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_core/executor/in_process.py", line 50, in execute
[2022-12-26T10:02:25.198+0000] {subprocess.py:93} INFO -     output_capture=plan_context.output_capture,
[2022-12-26T10:02:25.199+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_core/execution/api.py", line 1192, in __iter__
[2022-12-26T10:02:25.200+0000] {subprocess.py:93} INFO -     pipeline_context=self.pipeline_context,
[2022-12-26T10:02:25.200+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_core/execution/plan/execute_plan.py", line 115, in inner_plan_execution_iterator
[2022-12-26T10:02:25.201+0000] {subprocess.py:93} INFO -     dagster_event_sequence_for_step(step_context)
[2022-12-26T10:02:25.237+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_core/execution/plan/execute_plan.py", line 340, in dagster_event_sequence_for_step
[2022-12-26T10:02:25.240+0000] {subprocess.py:93} INFO -     raise dagster_user_error.user_exception
[2022-12-26T10:02:25.242+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_core/execution/plan/utils.py", line 56, in op_execution_error_boundary
[2022-12-26T10:02:25.247+0000] {subprocess.py:93} INFO -     yield
[2022-12-26T10:02:25.257+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_utils/__init__.py", line 458, in iterate_with_context
[2022-12-26T10:02:25.260+0000] {subprocess.py:93} INFO -     next_output = next(iterator)
[2022-12-26T10:02:25.263+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_core/execution/plan/compute_generator.py", line 75, in _coerce_solid_compute_fn_to_iterator
[2022-12-26T10:02:25.268+0000] {subprocess.py:93} INFO -     result = fn(context, **kwargs) if context_arg_provided else fn(**kwargs)
[2022-12-26T10:02:25.276+0000] {subprocess.py:93} INFO -   File "/opt/***/tasks/data_cleansing_basic_stat.py", line 22, in reading_json
[2022-12-26T10:02:25.279+0000] {subprocess.py:93} INFO -     df = pd.read_json("/opt/***/zone1/lol_basic_stat.json",lines=True)
[2022-12-26T10:02:25.291+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
[2022-12-26T10:02:25.297+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2022-12-26T10:02:25.302+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
[2022-12-26T10:02:25.304+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2022-12-26T10:02:25.307+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
[2022-12-26T10:02:25.312+0000] {subprocess.py:93} INFO -     return json_reader.read()
[2022-12-26T10:02:25.314+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 746, in read
[2022-12-26T10:02:25.330+0000] {subprocess.py:93} INFO -     obj = self._get_object_parser(self._combine_lines(data_lines))
[2022-12-26T10:02:25.340+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
[2022-12-26T10:02:25.351+0000] {subprocess.py:93} INFO -     obj = FrameParser(json, **kwargs).parse()
[2022-12-26T10:02:25.368+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
[2022-12-26T10:02:25.374+0000] {subprocess.py:93} INFO -     self._parse_no_numpy()
[2022-12-26T10:02:25.380+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
[2022-12-26T10:02:25.388+0000] {subprocess.py:93} INFO -     loads(json, precise_float=self.precise_float), dtype=None
[2022-12-26T10:02:25.393+0000] {subprocess.py:93} INFO - 
[2022-12-26T10:02:25.395+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-26T10:02:25.399+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_core/execution/plan/execute_plan.py", line 266, in dagster_event_sequence_for_step
[2022-12-26T10:02:25.402+0000] {subprocess.py:93} INFO -     for step_event in check.generator(step_events):
[2022-12-26T10:02:25.407+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_core/execution/plan/execute_step.py", line 389, in core_dagster_event_sequence_for_step
[2022-12-26T10:02:25.417+0000] {subprocess.py:93} INFO -     _step_output_error_checked_user_event_sequence(step_context, user_event_sequence)
[2022-12-26T10:02:25.420+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_core/execution/plan/execute_step.py", line 94, in _step_output_error_checked_user_event_sequence
[2022-12-26T10:02:25.428+0000] {subprocess.py:93} INFO -     for user_event in user_event_sequence:
[2022-12-26T10:02:25.433+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_core/execution/plan/compute.py", line 177, in execute_core_compute
[2022-12-26T10:02:25.443+0000] {subprocess.py:93} INFO -     for step_output in _yield_compute_results(step_context, inputs, compute_fn):
[2022-12-26T10:02:25.445+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_core/execution/plan/compute.py", line 154, in _yield_compute_results
[2022-12-26T10:02:25.447+0000] {subprocess.py:93} INFO -     user_event_generator,
[2022-12-26T10:02:25.452+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_utils/__init__.py", line 460, in iterate_with_context
[2022-12-26T10:02:25.455+0000] {subprocess.py:93} INFO -     return
[2022-12-26T10:02:25.457+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
[2022-12-26T10:02:25.459+0000] {subprocess.py:93} INFO -     self.gen.throw(type, value, traceback)
[2022-12-26T10:02:25.464+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_core/execution/plan/utils.py", line 91, in op_execution_error_boundary
[2022-12-26T10:02:25.466+0000] {subprocess.py:93} INFO -     ) from e
[2022-12-26T10:02:25.473+0000] {subprocess.py:93} INFO - dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "reading_json":
[2022-12-26T10:02:25.475+0000] {subprocess.py:93} INFO - 
[2022-12-26T10:02:25.479+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2022-12-26T10:02:25.485+0000] {subprocess.py:93} INFO - 
[2022-12-26T10:02:25.489+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-26T10:02:25.493+0000] {subprocess.py:93} INFO -   File "/opt/***/tasks/data_cleansing_basic_stat.py", line 95, in <module>
[2022-12-26T10:02:25.495+0000] {subprocess.py:93} INFO -     result = data_cleansing_whole_job.execute_in_process()
[2022-12-26T10:02:25.499+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_core/definitions/job_definition.py", line 394, in execute_in_process
[2022-12-26T10:02:25.508+0000] {subprocess.py:93} INFO -     asset_selection=frozenset(asset_selection),
[2022-12-26T10:02:25.530+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_core/execution/execute_in_process.py", line 77, in core_execute_in_process
[2022-12-26T10:02:25.546+0000] {subprocess.py:93} INFO -     event_list = list(execute_run_iterable)
[2022-12-26T10:02:25.553+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_core/execution/api.py", line 1192, in __iter__
[2022-12-26T10:02:25.562+0000] {subprocess.py:93} INFO -     pipeline_context=self.pipeline_context,
[2022-12-26T10:02:25.564+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_core/execution/api.py", line 1089, in pipeline_execution_iterator
[2022-12-26T10:02:25.567+0000] {subprocess.py:93} INFO -     for event in pipeline_context.executor.execute(pipeline_context, execution_plan):
[2022-12-26T10:02:25.571+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_core/executor/in_process.py", line 50, in execute
[2022-12-26T10:02:25.574+0000] {subprocess.py:93} INFO -     output_capture=plan_context.output_capture,
[2022-12-26T10:02:25.578+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_core/execution/api.py", line 1192, in __iter__
[2022-12-26T10:02:25.581+0000] {subprocess.py:93} INFO -     pipeline_context=self.pipeline_context,
[2022-12-26T10:02:25.584+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_core/execution/plan/execute_plan.py", line 115, in inner_plan_execution_iterator
[2022-12-26T10:02:25.588+0000] {subprocess.py:93} INFO -     dagster_event_sequence_for_step(step_context)
[2022-12-26T10:02:25.591+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_core/execution/plan/execute_plan.py", line 340, in dagster_event_sequence_for_step
[2022-12-26T10:02:25.593+0000] {subprocess.py:93} INFO -     raise dagster_user_error.user_exception
[2022-12-26T10:02:25.594+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_core/execution/plan/utils.py", line 56, in op_execution_error_boundary
[2022-12-26T10:02:25.595+0000] {subprocess.py:93} INFO -     yield
[2022-12-26T10:02:25.596+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_utils/__init__.py", line 458, in iterate_with_context
[2022-12-26T10:02:25.599+0000] {subprocess.py:93} INFO -     next_output = next(iterator)
[2022-12-26T10:02:25.602+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dagster/_core/execution/plan/compute_generator.py", line 75, in _coerce_solid_compute_fn_to_iterator
[2022-12-26T10:02:25.606+0000] {subprocess.py:93} INFO -     result = fn(context, **kwargs) if context_arg_provided else fn(**kwargs)
[2022-12-26T10:02:25.608+0000] {subprocess.py:93} INFO -   File "/opt/***/tasks/data_cleansing_basic_stat.py", line 22, in reading_json
[2022-12-26T10:02:25.611+0000] {subprocess.py:93} INFO -     df = pd.read_json("/opt/***/zone1/lol_basic_stat.json",lines=True)
[2022-12-26T10:02:25.613+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
[2022-12-26T10:02:25.616+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2022-12-26T10:02:25.617+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
[2022-12-26T10:02:25.620+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2022-12-26T10:02:25.621+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
[2022-12-26T10:02:25.622+0000] {subprocess.py:93} INFO -     return json_reader.read()
[2022-12-26T10:02:25.624+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 746, in read
[2022-12-26T10:02:25.630+0000] {subprocess.py:93} INFO -     obj = self._get_object_parser(self._combine_lines(data_lines))
[2022-12-26T10:02:25.632+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
[2022-12-26T10:02:25.634+0000] {subprocess.py:93} INFO -     obj = FrameParser(json, **kwargs).parse()
[2022-12-26T10:02:25.639+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
[2022-12-26T10:02:25.642+0000] {subprocess.py:93} INFO -     self._parse_no_numpy()
[2022-12-26T10:02:25.644+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
[2022-12-26T10:02:25.645+0000] {subprocess.py:93} INFO -     loads(json, precise_float=self.precise_float), dtype=None
[2022-12-26T10:02:25.646+0000] {subprocess.py:93} INFO - ValueError: Expected object or value
[2022-12-26T10:02:26.523+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2022-12-26T10:02:26.633+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-12-26T10:02:26.672+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=Can_I_change_name_to_this, task_id=basic_data_cleansing, execution_date=20221225T100000, start_date=20221226T100217, end_date=20221226T100226
[2022-12-26T10:02:26.747+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 268 for task basic_data_cleansing (Bash command failed. The command returned a non-zero exit code 1.; 164)
[2022-12-26T10:02:26.817+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-26T10:02:26.900+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
